language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "5"

install:
  - npm install
  - npm install -g nodeunit grunt-cli

script:
  - grunt

sudo: false

notifications:
  slack: cocolab-stanford:X2Ebs0qIMVUidJBD1xZd2XU1
