language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "5"

env:
  - TASK=default

matrix:
  include:
    - node_js: "5"
      env: TASK=travis-phantomjs

install:
  - npm install
  - npm install -g nodeunit grunt-cli
  - if [ $TASK = travis-phantomjs ]; then npm install -g browserify uglifyjs; fi
  - if [ $TASK = travis-phantomjs ]; then travis/install-phantomjs.sh; fi
  - if [ $TASK = travis-phantomjs ]; then export PATH=$PWD/phantomjs:$PATH; fi

script:
  - grunt $TASK

sudo: false

notifications:
  slack: cocolab-stanford:X2Ebs0qIMVUidJBD1xZd2XU1
